# Generated by Django 5.0.1 on 2024-02-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=30)),
                ('patient', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('time', models.TimeField(default=-19800)),
            ],
        ),
    ]
