# Generated by Django 5.0.1 on 2024-02-17 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HCapp', '0002_appointcopy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointcopy',
            old_name='patient',
            new_name='patient_name',
        ),
    ]
